---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - opsgenie.macpaw.dev
  resources:
  - opsgenieescalations
  - opsgenieschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opsgenie.macpaw.dev
  resources:
  - opsgenieescalations/finalizers
  - opsgenieschedules/finalizers
  verbs:
  - update
- apiGroups:
  - opsgenie.macpaw.dev
  resources:
  - opsgenieescalations/status
  - opsgenieschedules/status
  verbs:
  - get
  - patch
  - update
