//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieEscalation) DeepCopyInto(out *OpsgenieEscalation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieEscalation.
func (in *OpsgenieEscalation) DeepCopy() *OpsgenieEscalation {
	if in == nil {
		return nil
	}
	out := new(OpsgenieEscalation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpsgenieEscalation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieEscalationList) DeepCopyInto(out *OpsgenieEscalationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpsgenieEscalation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieEscalationList.
func (in *OpsgenieEscalationList) DeepCopy() *OpsgenieEscalationList {
	if in == nil {
		return nil
	}
	out := new(OpsgenieEscalationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpsgenieEscalationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieEscalationRecipient) DeepCopyInto(out *OpsgenieEscalationRecipient) {
	*out = *in
	if in.ScheduleRef != nil {
		in, out := &in.ScheduleRef, &out.ScheduleRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.TeamRef != nil {
		in, out := &in.TeamRef, &out.TeamRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieEscalationRecipient.
func (in *OpsgenieEscalationRecipient) DeepCopy() *OpsgenieEscalationRecipient {
	if in == nil {
		return nil
	}
	out := new(OpsgenieEscalationRecipient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieEscalationRule) DeepCopyInto(out *OpsgenieEscalationRule) {
	*out = *in
	in.Recipient.DeepCopyInto(&out.Recipient)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieEscalationRule.
func (in *OpsgenieEscalationRule) DeepCopy() *OpsgenieEscalationRule {
	if in == nil {
		return nil
	}
	out := new(OpsgenieEscalationRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieEscalationSpec) DeepCopyInto(out *OpsgenieEscalationSpec) {
	*out = *in
	if in.TeamRef != nil {
		in, out := &in.TeamRef, &out.TeamRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]OpsgenieEscalationRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieEscalationSpec.
func (in *OpsgenieEscalationSpec) DeepCopy() *OpsgenieEscalationSpec {
	if in == nil {
		return nil
	}
	out := new(OpsgenieEscalationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieEscalationStatus) DeepCopyInto(out *OpsgenieEscalationStatus) {
	*out = *in
	in.LastSyncedTime.DeepCopyInto(&out.LastSyncedTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieEscalationStatus.
func (in *OpsgenieEscalationStatus) DeepCopy() *OpsgenieEscalationStatus {
	if in == nil {
		return nil
	}
	out := new(OpsgenieEscalationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieIncidentCondition) DeepCopyInto(out *OpsgenieIncidentCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieIncidentCondition.
func (in *OpsgenieIncidentCondition) DeepCopy() *OpsgenieIncidentCondition {
	if in == nil {
		return nil
	}
	out := new(OpsgenieIncidentCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieIncidentProperties) DeepCopyInto(out *OpsgenieIncidentProperties) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Details != nil {
		in, out := &in.Details, &out.Details
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.StakeholderProperties.DeepCopyInto(&out.StakeholderProperties)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieIncidentProperties.
func (in *OpsgenieIncidentProperties) DeepCopy() *OpsgenieIncidentProperties {
	if in == nil {
		return nil
	}
	out := new(OpsgenieIncidentProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieIncidentResponder) DeepCopyInto(out *OpsgenieIncidentResponder) {
	*out = *in
	if in.ScheduleRef != nil {
		in, out := &in.ScheduleRef, &out.ScheduleRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.TeamRef != nil {
		in, out := &in.TeamRef, &out.TeamRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieIncidentResponder.
func (in *OpsgenieIncidentResponder) DeepCopy() *OpsgenieIncidentResponder {
	if in == nil {
		return nil
	}
	out := new(OpsgenieIncidentResponder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieIncidentRule) DeepCopyInto(out *OpsgenieIncidentRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieIncidentRule.
func (in *OpsgenieIncidentRule) DeepCopy() *OpsgenieIncidentRule {
	if in == nil {
		return nil
	}
	out := new(OpsgenieIncidentRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpsgenieIncidentRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieIncidentRuleList) DeepCopyInto(out *OpsgenieIncidentRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpsgenieIncidentRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieIncidentRuleList.
func (in *OpsgenieIncidentRuleList) DeepCopy() *OpsgenieIncidentRuleList {
	if in == nil {
		return nil
	}
	out := new(OpsgenieIncidentRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpsgenieIncidentRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieIncidentRuleSpec) DeepCopyInto(out *OpsgenieIncidentRuleSpec) {
	*out = *in
	if in.ServiceRef != nil {
		in, out := &in.ServiceRef, &out.ServiceRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]OpsgenieIncidentCondition, len(*in))
		copy(*out, *in)
	}
	in.IncidentProperties.DeepCopyInto(&out.IncidentProperties)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieIncidentRuleSpec.
func (in *OpsgenieIncidentRuleSpec) DeepCopy() *OpsgenieIncidentRuleSpec {
	if in == nil {
		return nil
	}
	out := new(OpsgenieIncidentRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieIncidentRuleStatus) DeepCopyInto(out *OpsgenieIncidentRuleStatus) {
	*out = *in
	in.LastSyncedTime.DeepCopyInto(&out.LastSyncedTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieIncidentRuleStatus.
func (in *OpsgenieIncidentRuleStatus) DeepCopy() *OpsgenieIncidentRuleStatus {
	if in == nil {
		return nil
	}
	out := new(OpsgenieIncidentRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieParticipant) DeepCopyInto(out *OpsgenieParticipant) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieParticipant.
func (in *OpsgenieParticipant) DeepCopy() *OpsgenieParticipant {
	if in == nil {
		return nil
	}
	out := new(OpsgenieParticipant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieRotation) DeepCopyInto(out *OpsgenieRotation) {
	*out = *in
	if in.Participants != nil {
		in, out := &in.Participants, &out.Participants
		*out = make([]OpsgenieParticipant, len(*in))
		copy(*out, *in)
	}
	if in.TimeRestriction != nil {
		in, out := &in.TimeRestriction, &out.TimeRestriction
		*out = new(OpsgenieTimeRestriction)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieRotation.
func (in *OpsgenieRotation) DeepCopy() *OpsgenieRotation {
	if in == nil {
		return nil
	}
	out := new(OpsgenieRotation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieSchedule) DeepCopyInto(out *OpsgenieSchedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieSchedule.
func (in *OpsgenieSchedule) DeepCopy() *OpsgenieSchedule {
	if in == nil {
		return nil
	}
	out := new(OpsgenieSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpsgenieSchedule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieScheduleList) DeepCopyInto(out *OpsgenieScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpsgenieSchedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieScheduleList.
func (in *OpsgenieScheduleList) DeepCopy() *OpsgenieScheduleList {
	if in == nil {
		return nil
	}
	out := new(OpsgenieScheduleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpsgenieScheduleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieScheduleSpec) DeepCopyInto(out *OpsgenieScheduleSpec) {
	*out = *in
	if in.Rotations != nil {
		in, out := &in.Rotations, &out.Rotations
		*out = make([]OpsgenieRotation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieScheduleSpec.
func (in *OpsgenieScheduleSpec) DeepCopy() *OpsgenieScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(OpsgenieScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieScheduleStatus) DeepCopyInto(out *OpsgenieScheduleStatus) {
	*out = *in
	in.LastSyncedTime.DeepCopyInto(&out.LastSyncedTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieScheduleStatus.
func (in *OpsgenieScheduleStatus) DeepCopy() *OpsgenieScheduleStatus {
	if in == nil {
		return nil
	}
	out := new(OpsgenieScheduleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieService) DeepCopyInto(out *OpsgenieService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieService.
func (in *OpsgenieService) DeepCopy() *OpsgenieService {
	if in == nil {
		return nil
	}
	out := new(OpsgenieService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpsgenieService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieServiceList) DeepCopyInto(out *OpsgenieServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpsgenieService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieServiceList.
func (in *OpsgenieServiceList) DeepCopy() *OpsgenieServiceList {
	if in == nil {
		return nil
	}
	out := new(OpsgenieServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpsgenieServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieServiceSpec) DeepCopyInto(out *OpsgenieServiceSpec) {
	*out = *in
	if in.TeamRef != nil {
		in, out := &in.TeamRef, &out.TeamRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieServiceSpec.
func (in *OpsgenieServiceSpec) DeepCopy() *OpsgenieServiceSpec {
	if in == nil {
		return nil
	}
	out := new(OpsgenieServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieServiceStatus) DeepCopyInto(out *OpsgenieServiceStatus) {
	*out = *in
	in.LastSyncedTime.DeepCopyInto(&out.LastSyncedTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieServiceStatus.
func (in *OpsgenieServiceStatus) DeepCopy() *OpsgenieServiceStatus {
	if in == nil {
		return nil
	}
	out := new(OpsgenieServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieStakeholderProperties) DeepCopyInto(out *OpsgenieStakeholderProperties) {
	*out = *in
	if in.Enable != nil {
		in, out := &in.Enable, &out.Enable
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieStakeholderProperties.
func (in *OpsgenieStakeholderProperties) DeepCopy() *OpsgenieStakeholderProperties {
	if in == nil {
		return nil
	}
	out := new(OpsgenieStakeholderProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieTeam) DeepCopyInto(out *OpsgenieTeam) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieTeam.
func (in *OpsgenieTeam) DeepCopy() *OpsgenieTeam {
	if in == nil {
		return nil
	}
	out := new(OpsgenieTeam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpsgenieTeam) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieTeamList) DeepCopyInto(out *OpsgenieTeamList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpsgenieTeam, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieTeamList.
func (in *OpsgenieTeamList) DeepCopy() *OpsgenieTeamList {
	if in == nil {
		return nil
	}
	out := new(OpsgenieTeamList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpsgenieTeamList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieTeamMember) DeepCopyInto(out *OpsgenieTeamMember) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieTeamMember.
func (in *OpsgenieTeamMember) DeepCopy() *OpsgenieTeamMember {
	if in == nil {
		return nil
	}
	out := new(OpsgenieTeamMember)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieTeamSpec) DeepCopyInto(out *OpsgenieTeamSpec) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]OpsgenieTeamMember, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieTeamSpec.
func (in *OpsgenieTeamSpec) DeepCopy() *OpsgenieTeamSpec {
	if in == nil {
		return nil
	}
	out := new(OpsgenieTeamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieTeamStatus) DeepCopyInto(out *OpsgenieTeamStatus) {
	*out = *in
	in.LastSyncedTime.DeepCopyInto(&out.LastSyncedTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieTeamStatus.
func (in *OpsgenieTeamStatus) DeepCopy() *OpsgenieTeamStatus {
	if in == nil {
		return nil
	}
	out := new(OpsgenieTeamStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieTimeInterval) DeepCopyInto(out *OpsgenieTimeInterval) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieTimeInterval.
func (in *OpsgenieTimeInterval) DeepCopy() *OpsgenieTimeInterval {
	if in == nil {
		return nil
	}
	out := new(OpsgenieTimeInterval)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpsgenieTimeRestriction) DeepCopyInto(out *OpsgenieTimeRestriction) {
	*out = *in
	if in.Intervals != nil {
		in, out := &in.Intervals, &out.Intervals
		*out = make([]OpsgenieTimeInterval, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpsgenieTimeRestriction.
func (in *OpsgenieTimeRestriction) DeepCopy() *OpsgenieTimeRestriction {
	if in == nil {
		return nil
	}
	out := new(OpsgenieTimeRestriction)
	in.DeepCopyInto(out)
	return out
}
